// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  footer_item: dynamic(() => import('./FooterItem')),
  hero_secrion: dynamic(() => import('./HeroSection')),
  more_effective: dynamic(() => import('./MoreEffective')),
  prices_section: dynamic(() => import('./PricesSection')),
  // rich_text: dynamic(() => import("./RichText")),
  section_logos: dynamic(() => import('./SectionLogos')),
  sign_up_section: dynamic(() => import('./SignUpSection')),
  streamlined_section: dynamic(() => import('./StreamlinedSection')),
  text: dynamic(() => import('./ListItem')),
  user_comments_section: dynamic(() => import('./UserCommentsSection')),
};
