// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_secrion: dynamic(() => import("./HeroSection")),
  rich_text: dynamic(() => import("./RichText")),
};
